### ISSUE TITLE
Documento de arquitetura

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#14]
# Descrição
Criação do documento de arquitetura e adição dos diagramas.

# Tarefas
- [ ] Criar um documento que contem uma visao geral sobre a arquitetura que sera ultilizada no projeto

# Critérios de aceitação
- [ ] Arquivo deve estar pronto e presente no repositorio

**Comment by hannanhunny01** [comment]
- [ ] Documento que contem uma visao geral sobre a arquitetura que sera ultilizada no projeto
- [ ]  Arquivo deve estar pronto e presente no repositorio
o documento inicial para a arquitetura de software foi criado e foi adicionado no repositório
