### ISSUE TITLE
Documento de visão

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#17]
# Descrição
Criação do documento de visao.
Explicar o objetivo do projeto.

# Tarefas
- [x] Criar um documento que contem uma visao geral sobre a arquitetura que sera ultilizada no projeto

# Critérios de aceitação
- [x] Arquivo deve estar pronto e presente no repositorio

**Comment by MatheusHenrickSantos** [comment]
O documento foi adicionado na pasta Docs. Resta agora preencher o tópico 7, sobre requisitos, que será feito posteriormente.
