### ISSUE TITLE
Prototipo de alta fidelidade

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#18]
# Descrição
Criar um prototipo de alta fidelidade, para dar uma cara definitiva para o projeto

# Tarefas
- [x] Criar um prototipo no figma.

# Critérios de aceitação
- [x] Deve ser baseado nos opnioes de todos os participantes.

**Comment by asafesouza** [comment]
O primeiro protótipo de alta fidelidade foi criado utilizando o Figma. E é baseado na média de todas as versões dos protótipos de baixa fidelidade
