### ISSUE TITLE
Criação do webcrawler

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#19]
# Descrição
Configurar o webcrawler inicial do projeto.

# Tarefas
- [ ] Criar um webcrawler funcional para o projeto.

# Critérios de aceitação
- [ ] Webcrawler deve ter a capacidade de comunicar com o backend.

**Comment by hannanhunny01** [comment]
- [ ] web crawler incial usando scrapy e splash foi criado e foi adcionando no respositorio do projeto

funcionalidades desse crawler atual sao:
carregue o javascript e espere o html renderizar e  copie todo o html do pagina selecionada.
