### ISSUE TITLE
Implementacao do 2º Web crawler

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#25]
**Web crawler**
Um web crawler para fazer a pesquisa dos nomes no site do cebraspe.

**Metodos**
Uso do scrapping e do selenium para implementacao.

**Comment by hannanhunny01** [comment]
crawler 2 inicial com funcionanlidade de pesquiar nomes dos usuario no paginas de chamadas para PAS usando middleware scrapy-selenium  foi criado e adcionado no respositorio do github
