### ISSUE TITLE
Revisao do documento de arquitetura

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#26]
# Descrição
Atualizar o documento de arquitetura do projeto

# Tarefas
- [x] Atualizar documento com as tecnologias escolhidas para projeto

# Critérios de aceitação
- [x] Documento de arquitetura deve estar de acordo com o projeto

**Comment by hannanhunny01** [comment]
uml de classes e uml de pacotes foram adicionado ao documento de arquitetura

**Comment by hannanhunny01** [comment]
documento de arquitetura foi atualizado
