### ISSUE TITLE
Atualizar o documento visao

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#28]
# Descrição
Atualizar o documento de visao com os requisitos

# Tarefas
- [x] Acrescentar o documento de visao com os requisitos escolhidos pela equipe

# Critérios de aceitação
- [x] Terminar documento de visao

**Comment by MatheusHenrickSantos** [comment]
O documento de visão está completo. Já adicionei o tópico que faltava, sobre requisitos.

**Comment by hannanhunny01** [comment]
requisitos de  software funcionais e nao-funcionais foram ataulizados .
