### ISSUE TITLE
Documentar Protótipos na github pages

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#41]
# Descrição
Expor os prototipos do projeto no github pages
# Tarefas
- [x] Os prototips devem estar visiveis no githgub pages 
- [x] faça um documento Prototpitpo.md e Adicione os dois prototipos de Alta e baixa quailidade nele

**Comment by hannanhunny01** [comment]
Arquivo Prototipo.md foi criado no branch github pages  e foi adcionada para a páginas do github, para mais detalhes verifique os comentários do commits
