### ISSUE TITLE
Criar e documentar quadro de conhecimento

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#45]
# Descrição
- [x] Criação de documento do Quadro de conhecimento para definir o conhecimento de cada participante em tecnologias que vamos usar no projeto.

- [ ] adicione e configure este documento na no github pages.

**Comment by hannanhunny01** [comment]
documento para quadro de conhecimento foi criado 
link para docuemento:
https://docs.google.com/spreadsheets/d/1ojHMnG0qsWHCXixu1T1vIjtYN6Ih6vUa-awpGTaRoFg/edit#gid=1642377366

**Comment by hannanhunny01** [comment]
Quadro de conhecmento foi criado e adcionado no github page
