### ISSUE TITLE
Documentar documento de visao e de arquitetura no Github pages

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#48]
# Descrição
[Descrever brevemente os objetivos da issue]

# Tarefas
- [ ] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

# Critérios de aceitação
- [ ] Critério 1
- [ ] Critério 2
- [ ] Critério 3

**Comment by hannanhunny01** [comment]
documentos e arquitetura e visao foram adcionado no brach para github page mais detalhes estao no comentario para commit
