### ISSUE TITLE
Implementação e Construção dos Pipelines para Spider1

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#63]
# Descrição
Construir uma aranha para numerar a contagem de links no site e verificar se ouve uma atualizacao no numero de links disponiveis.

# Tarefas
- [x] Construir uma aranha contadora de links

# Critérios de aceitação
- [x] A aranha deve contar a quantidade de links no site do cebraspe
- [x] A aranha deve comparar com a quantidade sava no banco de dados

**Comment by hannanhunny01** [comment]
Spider para numerar a contagem de links no site e verificar se ouve uma atualizacao no numero de links disponiveis foi implementado junto com os pipeline e banco de dados usando mongodb
