### ISSUE TITLE
Implantação e Construção de Pipelines para Spider2 e Spider 3

### ISSUE THREAD

**Issue by HacKairos** [fga-eps-mds/Cebraspe-Tracker#70]
# Descrição
Construir spider 2 e 3 um para a contagem de links de chamada  no site e verificar se ouve uma atualizacao no numero de links disponiveis.
E outra para pesquisar nomes dos pessoas registrado no banco de dado nas chamadas do pas unb 

# Tarefas
- [x] Construir uma aranha contadora de links
- [x]  Contruir uma aranha que pesquisa nome das pessoas em chamadas do Pas/unb 

# Critérios de aceitação
- [x]  Spider2 deve contar a quantidade de links no site do cebraspe
- [x]  Spider2 deve salva links no banco de dados
- [x]   Spider3 deve pesquisar nomes das pessoas salvado em banco de dados 
- [x]  Spider3 Deve salvar resultado(se o nome foi encontra na chamada do pas/unb)

**Comment by hannanhunny01** [comment]
Spider 2 e 3 foram criados e todos os  tarefas foram feitas
